component_depth: 1
languages:
- java
- javascript

exclude:
- .*/d3.*
- .*/input.*
- .*/vim.*
- .*/smarty.*
- .*/multiplex.*
- .*/codemirror.*
- .*/haxe.*
- .*/bootstrap.*
- .*/CodeFiles.*
- .*/outputWarningsJSON.*
- .*/outputCodeJSON.*
- .*/CodeFiles.*
  
